### ISSUE TITLE
Invalid weight unit error when tyring to edit T-shirt variations

### ISSUE THREAD

**Issue by StevenWill** [mglaman/commerce_examples#26]
After a clean install of Drupal 8.4.2 and installation of commerce_demo I am receiving a error when I try to edit the t-shirt variation.  This is the error message...

InvalidArgumentException: Invalid weight unit " oz" provided. in Drupal\physical\WeightUnit::assertExists() (line 57 of /var/www/html/docroot/web/modules/contrib/physical/src/WeightUnit.php).

**Comment by mglaman** [comment]
I noticed this and need to fix. It's importing the "oz" value incorrecrlt.

**Comment by mglaman** [comment]
Yeah, it's including the whitespace on https://github.com/mglaman/commerce_demo/blob/master/data/demo_t_shirts.csv if we remove the whitespace os ` oz` becomes `oz`

**Comment by mglaman** [comment]
Fixed this a while ago.
